postgre:
  datasource:
    jdbc-url: jdbc:postgresql://${POSTGRE_DB_HOST}:${POSTGRE_DB_PORT}/${POSTGRE_DB_NAME}
    username: ${POSTGRE_DB_USERNAME}
    password: ${POSTGRE_DB_PASSWORD}
    pool-size: 30